### ISSUE TITLE
Double backslashes in the bind event breaks the JSON encoding.

### ISSUE THREAD

**Issue by stephan-v** [chinloyal/pusher_client#1]
First of all thanks a lot for this amazing library. I have been using this to trigger pusher client events and send over location data for a realtime map and it is working like a charm.

I am using this in conjuction with Laravel and most of the Laravel events are namespace like this:

`Illuminate\Notifications\Events\BroadcastNotificationCreated`

I can try to escape the backslashes by escaping the backslashes with this format but this still breaks the JSON encoding.

`Illuminate\\Notifications\\Events\\BroadcastNotificationCreated`

In that case I get the message:

`E/PusherClientPlugin(13562): Unterminated object at character 22 of {eventName=Illuminate\Notifications\Events\BroadcastNotificationCreated, channelName=orders}`

Somehow at that point when binding the backslashes are removed again, what could be the case for this and is there a way to resolve this?

**To reproduce you can simply subscribe to any channel and bind to a event like this:**

`Illuminate\\Notifications\\Events\\BroadcastNotificationCreated`

**Comment by chinloyal** [comment]
Thanks for raising this, I'll try to reproduce and resolve this.

**Comment by chinloyal** [comment]
@stephan-v Fixed
