### ISSUE TITLE
Can't get it work using SSL

### ISSUE THREAD

**Issue by Bojmaliev** [chinloyal/pusher_client#18]
I'm getting this exception when trying to connect to private or presence channel.

`W/System.err( 9862): com.pusher.client.AuthorizationFailureException: javax.net.ssl.SSLException: Unable to parse TLS packet header
W/System.err( 9862): 	at com.pusher.client.util.HttpAuthorizer.authorize(HttpAuthorizer.java:146)
W/System.err( 9862): 	at com.pusher.client.channel.impl.PrivateChannelImpl.getAuthResponse(PrivateChannelImpl.java:130)
W/System.err( 9862): 	at com.pusher.client.channel.impl.PrivateChannelImpl.toSubscribeMessage(PrivateChannelImpl.java:90)
W/System.err( 9862): 	at com.pusher.client.channel.impl.ChannelManager$1.run(ChannelManager.java:149)
W/System.err( 9862): 	at com.pusher.client.util.Factory$1.run(Factory.java:119)
W/System.err( 9862): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err( 9862): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err( 9862): 	at java.lang.Thread.run(Thread.java:923)
W/System.err( 9862): Caused by: javax.net.ssl.SSLException: Unable to parse TLS packet header
W/System.err( 9862): 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:807)
W/System.err( 9862): 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
W/System.err( 9862): 	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
W/System.err( 9862): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:849)
W/System.err( 9862): 	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:722)
W/System.err( 9862): 	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:238)
W/System.err( 9862): 	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:217)
W/System.err( 9862): 	at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:196)
W/System.err( 9862): 	at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
W/System.err( 9862): 	at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
W/System.err( 9862): 	at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
W/System.err( 9862): 	at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
W/System.err( 9862): 	at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
W/System.err( 9862): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
W/System.err( 9862): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
W/System.err( 9862): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
W/System.err( 9862): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
W/System.err( 9862): 	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
W/System.err( 9862): 	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
W/System.err( 9862): 	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
W/System.err( 9862): 	at com.pusher.client.util.HttpAuthorizer.authorize(HttpAuthorizer.java:122)`

**Comment by Bojmaliev** [comment]
I fixed this using flutter clean and re-build project ....

**Comment by YassineChe** [comment]
Can you show me a snippet of your code using SSL ?
