### ISSUE TITLE
IOS : Unable to parse string as JSON - check that your JSON is valid.

### ISSUE THREAD

**Issue by heshesh2010** [chinloyal/pusher_client#21]
Hi , I'm using :   flutter_pusher: ^1.0.2

here is my flutter doctor : 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 2.2.0-10.2.pre, on macOS 11.2.3 20D91 darwin-x64, locale en-EG)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)

• No issues found!

when bind to new event on pusher console i got in xcode : 

2021-05-09 21:16:44.921819+0200 Runner[51749:732568] Metal API Validation Enabled
2021-05-09 21:16:45.079714+0200 Runner[51749:732999] flutter: Observatory listening on http://127.0.0.1:58979/NtaMnrrTlHQ=/
Pusher init
Pusher connect
2021-05-09 21:19:55.961112+0200 Runner[51749:738889] [] nw_protocol_get_quic_image_block_invoke dlopen libquic failed
Pusher subscribe
Pusher bind (Conversation)
Unable to parse string as JSON - check that your JSON is valid.
Unable to parse string as JSON - check that your JSON is valid.

**Comment by chinloyal** [comment]
`flutter_pusher: ^1.0.2` is not this repository's package. To use the latest version of this package use `pusher_client: ^1.1.3`
