### ISSUE TITLE
How can i make a pusher.connection.state equivalent in this package?

### ISSUE THREAD

**Issue by astrO1** [chinloyal/pusher_client#23]
I'm searching on documentation and I don't find it anywhere. If not implemented how can I make this work in this package?

**Comment by abinvp** [comment]
This would be a great addition. Apparently, we can listen to state changes but there isn't a way to identify the current state at any point.

**Comment by chinloyal** [comment]
@astrO1 This seems like a javascript API. This package is mainly focused on making the APIs more similar to Java or Swift. If you want to know the state use [`onConnectionStateChange`](https://github.com/pusher/pusher-websocket-java#listening-to-connection-events) listener, it gives you access to the current state and the previous state
