### ISSUE TITLE
Why include log4j12 dependency?

### ISSUE THREAD

**Issue by spiritinlife** [chinloyal/pusher_client#3]
I am considering using this library, but i am not sure why is log4j12 used?

**Comment by spiritinlife** [comment]
Also when minifyEnabled=true, i get  Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.log4j.Category" on path: DexPathList

**Comment by chinloyal** [comment]
The configuration for this is mentioned in the read me [here](https://github.com/chinloyal/pusher_client#for-android) It speaks to what to do if minifyEnabled is true

**Comment by chinloyal** [comment]
I may have installed it for logging but I'm realizing that I had used `android.util.Log` instead so I may have installed log4j but forgot to remove it.

**Comment by chinloyal** [comment]
I'll remove it
