### ISSUE TITLE
connect failed: ETIMEDOUT (Connection timed out)

### ISSUE THREAD

**Issue by DevTiago** [chinloyal/pusher_client#54]
Hello there, 

This isn't a package error because the package is working in all devices except on a **Xiaomi Redmi Note 7**.

the 'onConnectionError' method catch this error:

```
message: An exception was thrown by the websocket
code: null
Exception: failed to connect to websockets.************.pt/2001:bc8:4700:2300::29:503 (port 443) from /:: (port 42860): connect failed: ETIMEDOUT (Connection timed out)
```

Anyone has faced the same problem? Any guess?

**Comment by YassineChe** [comment]
Bizarre!
for me i'm getting `java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`
You didn't face it ?

**Comment by DevTiago** [comment]
Well, this can be closed... it's a problem with the connection between some devices (eg: Xiaomi) and the server.

Usually devices use IPV4 to connect to server and apparently Xiaomi uses IPV6... and the IPV6 of the server i use was changed so that was the problem.

**Comment by YassineChe** [comment]
@DevTiago,

I solved the problem, still on it ?
