### ISSUE TITLE
Android: Binding to channel events cancels calls to onConnectionStateChange etc

### ISSUE THREAD

**Issue by gertdrui** [chinloyal/pusher_client#7]
When binding to events on channels I receive no callbacks for onConnectionStateChange. If I don't bind to events I successfully receive callbacks. 

It appears each bind adds a new listener to the EventChannel, however on the Android side each new listener replaces the previous `PusherService.eventSink`, so I assume that is why multiple listeners are not actually working.

**Comment by chinloyal** [comment]
What version of this package are you using?

**Comment by gertdrui** [comment]
v1.1.2

**Comment by chinloyal** [comment]
The `onConnectionStateChange` method gets triggered once you initialize the `PusherClient` constructor with autoconnect set to true. Or when you call `.connect()` on an instance of `PusherClient`. It doesn't get triggered when binding to an event or channel.

**Comment by chinloyal** [comment]
As stated in the readme for this package you can bind to internal pusher events like `pusher:subscription_succeeded` this lets you know when a subscription to a channel has succeeded. (See under "Binding to events")

**Comment by gertdrui** [comment]
Logs from the native side indicate that I am connected and I'm receiving events from my subscribed channels, however when I use `bind`, the onConnectionStateChange callbacks never reach flutter. 

Without using bind, I do receive callbacks on onConnectionStateChange.

I'm coming from using pusher_websocket_flutter which uses one receiveBroadcastStream() listener to handle all incoming event types, be it connection state changes or actual channel events. 

This plugin looks similar, but the big difference being that each bind also adds a listener to receiveBroadcastStream(), and on the native side this replaces the eventSink, which is ok for pusher_websocket_flutter's single listener, but I'd suspect not for this plugin?

**Comment by chinloyal** [comment]
Yes, onConnectionStateChange callbacks are not triggered when you use `bind`. As stated on the comment for `onConnectionStateChange`.

```dart
  /// Callback that is fired whenever the connection state of the
  /// connection changes. The state typically changes during connection
  /// to Pusher and during disconnection and reconnection.
  void onConnectionStateChange(void Function(ConnectionStateChange state) callback)
```

So the state will never change on `bind`

**Comment by chinloyal** [comment]
What exactly are you trying to achieve?

**Comment by gertdrui** [comment]
Sorry for the confusion, what I'm trying to communicate is that ConnectionStateChanges like 'CONNECTED', 'DISCONNECTED', 'RECONNECTING' are not reaching flutter, after using `bind`. 

I don't expect connection state changes to be triggered because of bind, but what I'm saying is that normal connection state changes no longer reach flutter after I do.

this works:
pusher.connect();
pusher.onConnectionStateChange((state) { print('state change'); });

this does not, state change will never get called on flutter, but I can see it in native logs:
pusher.connect();
pusher.onConnectionStateChange((state) { print('state change'); });
channel = pusher.subscribe('my-channel');
channel.bind('my-event', (_) {});

**Comment by chinloyal** [comment]
Oh OK I think I get it. I'll try to reproduce and resolve
