### ISSUE TITLE
failed to connect to ip6-localhost/::1

### ISSUE THREAD

**Issue by ujwalbasnet1** [chinloyal/pusher_client#9]
{message: An exception was thrown by the websocket, code: null, exception: failed to connect to ip6-localhost/::1 (port 80) from /:: (port 45290): connect failed: ECONNREFUSED (Connection refused)}

**Comment by ujwalbasnet1** [comment]
it was due to missing cluster value

**Comment by parthjdabhi** [comment]
If you are using a custom host, you can just go ahead and skip the cluster value. An empty cluster value is also making this error.
